import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsBoolean, IsObject, IsOptional } from 'class-validator';

export class ImportConfigDto {
  @ApiPropertyOptional({
    description: 'If true, existing user config is replaced before import',
    default: false
  })
  @IsOptional()
  @IsBoolean()
  replace?: boolean;

  @ApiProperty({
    description: 'Config payload generated by /system/config/export'
  })
  @IsObject()
  config!: Record<string, unknown>;
}
